version: "3.3"
services:
  app-lin:
    container_name: app-lin
    hostname: app-lin
    build: ./Docker/App
    ports:
      - 98:80
      - 9010:9001
    volumes:
      - ./:/var/www/app
    restart: unless-stopped
