<?php

namespace Tests\Unit;

use App\Exceptions\InvalidNameException;
use PHPUnit\Framework\TestCase;
use App\Data\Validators;

/**
 * @package Tests
 * @group unit
 * @group ready
 */
class ValidatorsTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testAmountValidator()
    {
        $this->assertTrue(Validators\AmountValidator::validateAmount(452.36));
        $this->assertTrue(Validators\AmountValidator::validateAmount(0.36, 0.1));
        $this->assertFalse(Validators\AmountValidator::validateAmount(-23.5));
    }

    public function testNameValidator()
    {
        $this->assertTrue(Validators\NameValidator::validateName('JustTesting'));
    }

    public function testNameValidatorException()
    {
        $this->expectException('App\Exceptions\InvalidNameException');
        Validators\NameValidator::validateName('"DROP TABLE X;');
    }

    public function testAmountValidatorException()
    {
        $this->assertFalse(Validators\AmountValidator::validateAmount(-0.36, 0.1));
    }
}
